### PR TITLE
Memory leak when the ResultSet be closed

### PR DESCRIPTION
**Pull request by StefanXiepj**
issues: https://github.com/datanucleus/datanucleus-api-jdo/issues/106

### CODE REVIEW

**Comment by StefanXiepj** [comment]
@andyjefferson Can you help me to review this pr?

**Comment by StefanXiepj** [comment]
Thank you very much, your repair is so perfect, i like it

**Comment by StefanXiepj** [comment]
Can you fix it in version 4.2.1 and publish a release version?

**Comment by andyjefferson** [comment]
5.2 is the ONLY maintained branch

**Pull request merged**
